version: "3"
services:
  web:
    build: .
    ports:
      - "5656:5656"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/robotschaingo
    depends_on:
      - mongo
    command: npm test
  mongo:
    image: mongo
    ports:
      - "27017:27017"
